version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5002:5000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
